### ISSUE TITLE
Timeout exception

### ISSUE THREAD

**Issue by iamalisajid** [klaviyo/python-klaviyo#12]
How to get the timeout exception, I haven't seen any exception regarding this

**Comment by remstone7** [comment]
@iamalisajid could you specify a bit more and provide an example?

**Comment by iamalisajid** [comment]
E.g I'm sending an identify request to Klaviyo and somehow the request times out, klaviyo raises no exception. I just want to handle that exception or maybe a timeout can be added to `_request` method.

**Comment by iamalisajid** [comment]
I'll love to contribute though.

**Comment by remstone7** [comment]
makes sense, please feel free to contribute!

**Comment by remstone7** [comment]
closing for release of new version
