### ISSUE TITLE
all_members and all other batch request parameters coded incorrectly

### ISSUE THREAD

**Issue by billhumanlytics** [klaviyo/python-klaviyo#13]
Hi, 

the all_members function and all other functions with the "marker" parameter seem to be coded incorrectly as the marker is really not used by the system. 

Recommend change from the following: 

```
all_members = self._request('group/{}/members/all'.format(group_id), {}, api_version=api_version)
```

To the following:

```
params = {'marker': marker } if marker else {}
all_members = self._request('group/{}/members/all'.format(group_id), params, api_version=api_version)
```

Thanks, 
Bill

**Comment by remstone7** [comment]
Hey Bill, you're correct, it's been on our list to get done, would you like to contribute and i'll approve and bump?

**Comment by billhumanlytics** [comment]
@remstone7 sure, I will look it over and see if there are other cases. Probably will be during the weekend or later this week that I will submit a pull request.

**Comment by ga1205** [comment]
I just realized this is the same as the issue I just reported.  I'll mark mine duplicative.  Has this ever been updated?  Thanks!

**Comment by ga1205** [comment]
> @remstone7 sure, I will look it over and see if there are other cases. Probably will be during the weekend or later this week that I will submit a pull request.

Bill -- I tried taking the code you have above and passing it in but it's still not working for me.  I used `client.all_members("LIST_ID", marker='12345')` and it still returned the same first 1k records.

My updated __init__.py:
```
 def all_members(self, group_id, marker=None):
        """
        args:
            id: str() the list id or the segment id
            marker: int() optional returned from the previous get call
        """
        api_version = 'v2'
        # Update from GitHub Issue #13
        params = {'marker': marker } if marker else {}
        all_members = self._request('group/{}/members/all'.format(group_id), params, api_version=api_version)
        #all_members = self._request('group/{}/members/all'.format(group_id), {}, api_version=api_version)
        return all_members
```

Does that look correct?  Thanks!

**Comment by remstone7** [comment]
will make a pr for this now

**Comment by ga1205** [comment]
Thanks for fixing this!  I'm curious about a way to pull in all event history for a profile.  I was able to pull all IDs within a list but now I want to loop over that and pull down their event history.  Is that possible and, if so, what API limits do we need to be aware of?  I've got a few hundred thousand profiles to deal with.  

Thanks again!

**Comment by remstone7** [comment]
@ga1205 just pushed onto the same PR to add the profiles endpoint, this way you can use the `client.get_profile_metrics_timeline` method once you have a profile id https://github.com/klaviyo/python-klaviyo/pull/16/files#diff-b72a80f7ed9c628f3493d06280071aa2R263

**Comment by ga1205** [comment]
> @ga1205 just pushed onto the same PR to add the profiles endpoint, this way you can use the `client.get_profile_metrics_timeline` method once you have a profile id https://github.com/klaviyo/python-klaviyo/pull/16/files#diff-b72a80f7ed9c628f3493d06280071aa2R263

LGTM!  Thanks for the quick update.

**Comment by remstone7** [comment]
sure to pull in event history what i would recommend doing would be something like:

```
In [3]: client = Klaviyo(public_token='PUBLIC_KEY', private_token='PRIVATE_API_KEY')

In [4]: list_members = client.all_members(group_id='LIST_ID')

In [5]: list_members
Out[5]: {u'records': [{u'email': u'remstone7+13232@gmail.com', u'id': u'PROFILE_ID'}]}

In [6]: for member in list_members['records']:
   ...:     print client.get_profile_metrics_timeline(member['id'])
```

you will need to pass in the profile ID that is returned from the all members section, should be a 6 char string

**Comment by remstone7** [comment]
@ga1205  to your comment you must pass in the ID of the profile / metric and not the string!

**Comment by ga1205** [comment]
I passed that, but it didn't work.  I had it both in the function and as variables shown below:

```
profID = 'H4PyNS'
metricID = 'LsHZyj'

client.get_profile_metric_timeline(profID,metricID)
```
Here's the error:
```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-50-d070a5c97d47> in <module>
      2 metricID = 'LsHZyj'
      3 
----> 4 client.get_profile_metric_timeline(profID,metricID)

~/anaconda3/lib/python3.7/site-packages/klaviyo/__init__.py in get_profile_metric_timeline(self, profile_id, metric_id, since, count, sort)
    294         params = self._filter_params(params)
    295 
--> 296         return self._request('person/{}/metrics/{}/timeline'.format(profile_id, metric_id), params)
    297 
    298     ######################

~/anaconda3/lib/python3.7/site-packages/klaviyo/__init__.py in _request(self, path, params, method, api_version)
    379                     response = getattr(requests, method.lower())(url, headers=headers)
    380 
--> 381                 return response.json()
    382 
    383             elif method.upper() in CUD_REQUEST_TYPE:

~/anaconda3/lib/python3.7/site-packages/requests/models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

~/anaconda3/lib/python3.7/site-packages/simplejson/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    516             parse_constant is None and object_pairs_hook is None
    517             and not use_decimal and not kw):
--> 518         return _default_decoder.decode(s)
    519     if cls is None:
    520         cls = JSONDecoder

~/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py in decode(self, s, _w, _PY3)
    368         if _PY3 and isinstance(s, bytes):
    369             s = str(s, self.encoding)
--> 370         obj, end = self.raw_decode(s)
    371         end = _w(s, end).end()
    372         if end != len(s):

~/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py in raw_decode(self, s, idx, _w, _PY3)
    398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by remstone7** [comment]
yes, fixing https://github.com/klaviyo/python-klaviyo/pull/17
