### ISSUE TITLE
[Feature Request] Being able to get details of a segment list in v2 of api

### ISSUE THREAD

**Issue by billhumanlytics** [klaviyo/python-klaviyo#14]
Hi, 

I am just wondering if there is a way to get the subscriber count of a segment list. This was supported in V1, but now V1 is deprecated it seems that V2 no longer support getting segment lists (it returns a "list not found" error). 

Right now the only way that I can figure out is to get all members of a list and count them, but this places a heavy load on the server for something that should only take one request. 

Thanks, 

Bill

**Comment by njparadis** [comment]
Closing this out - once this feature is available it will be added to the SDK.
