### ISSUE TITLE
Sort parameter in metrics api broken?

### ISSUE THREAD

**Issue by cdswindell** [klaviyo/python-klaviyo#19]
When I use 'asc' as the value for the sort param in the metrics api, I get an empty list returned (count = 0) when there is no since param passed in.

**Comment by remstone7** [comment]
This is expected, it's how the api works it sorts from the since param.

If you do `client.metrics_timeline` it does from now and then would sort all `desc` from the now timestamp. it kind of goes on either side of the date rather than changing the order of the response
