### ISSUE TITLE
No way to know if API hit it's rate limit

### ISSUE THREAD

**Issue by tkrevh** [klaviyo/python-klaviyo#20]
Using the `client.list_subscription` API, there is no way to know the response status_code, because the API returns a JSON representation of the response.text (or '1' if response.text is empty).
Without receiving the status code, could you please let us know, how can we know if we're getting throttled? (so that we can exponentially back off with requests)

**Comment by remstone7** [comment]
we will soon release 3.0 and that will through a KlaviyoRateLimitException with appropriate details.. for now if you get rate limited via list v2 you would see a json response of something like:
```
{'detail': 'Request was throttled. Expected available in 56.0 seconds.'}
```

**Comment by remstone7** [comment]
https://github.com/klaviyo/python-klaviyo/pull/18

**Comment by tkrevh** [comment]
I think [HTTP status code 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) is a common solution for the rate limiting responses. Maybe you could either return the complete response (instead of just JSON or "1") and let users decode it. Or return an object, containing the status code and any JSON data. For now I've subclassed your Klaviyo class and overwritten the _request method, to return the response object. But according to your last response, we may not see 429 status code anyway.

**Comment by remstone7** [comment]
yes, you will only see it for the list v2 api as of now

**Comment by negrusti** [comment]
@remstone7 when can we expect 3.0? I the the responses fundamentally broken at the moment. At the very least I'd expect the status code returned for all API calls.

**Comment by remstone7** [comment]
@negrusti still working on it and taking some feedback from here and adding to it.  I would say ~2 weeks.  Is there something you can't figure out or have questions on that I could assist with in the meantime?

**Comment by tkrevh** [comment]
@negrusti I solved it temporarily by subclassing the Klaviyo class and overwriting it's _request method, so it returns the response and then work with that instead.

**Comment by remstone7** [comment]
resolved and closing for release of new version
