### ISSUE TITLE
'since' argument doesn't work as expected in get_profile_metrics_timeline method

### ISSUE THREAD

**Issue by vivekbharadwaj** [klaviyo/python-klaviyo#21]
Hi team. Thanks for the amazing work on this client for the Klaviyo API. 

When I try to0 get profile metrics information using the method `client.get_profile_metric_timeline`, and include a Unix timestamp for April 1st 2020 in the `since` argument : 
- **Expected behaviour:**  get the timeline of all metrics for that profile id FROM April 1st 2020 until current UTC time, as mentioned in the documentation https://www.klaviyo.com/docs/api/people#metrics-timeline
- **Actual behaviour:** get the timeline of all metrics for that profile id FROM the beginning of time UNTIL April 1st 2020

This behaviour was consistent for me, regardless of the sort order.

### Steps to replicate: 
```python
ts_since = (pd.to_datetime('2020-04-01')-pd.Timestamp('1970-01-01')) // pd.Timedelta('1s')  
req = client.get_profile_metrics_timeline(profile_id=<profile_id>, since=ts_since, sort='desc')
```

Looking forward to your assistance if I'm missing something obvious or if this argument is not working as expected? 

Thanks!

**Comment by remstone7** [comment]
@vivekbharadwaj looking into this, seeing some weird behaviour as well - doesn't appear to be due to the package as i was able to replicate just utilizing raw requests.  i'll follow up!

**Comment by remstone7** [comment]
@vivekbharadwaj the issue is with the underlying api here not the package, we will work to resolve this and will follow up here when completed

**Comment by vivekbharadwaj** [comment]
Thank you! figured it was because of the API because there was nothing fancy happening in the code. Appreciate the comments, and looking forward to a resolution. :)
