### ISSUE TITLE
Returning class object instead of the data dict

### ISSUE THREAD

**Issue by chirags1502** [klaviyo/python-klaviyo#23]
@remstone7 since the refactoring, it looks like we are returning the class in __handle_200_response (api_helper.py):

```
try:
            return KlaviyoAPIResponse(status_code, response.json())
```

Which needs the `.data` instance attribute to be accessed for the expected dictionary response:

```
print(client.Metrics.get_metrics(page=0,
                                 count=1).data)

```

> {'end': 0, 'object': '$list', 'page_size': 1, 'start': 0, 'total': 18, 'data': [{'updated': '2019-11-05 16:11:39', 'name': 'Active on Site', 'created': '2019-11-05 16:11:39', 'object': 'metric', 'id': 'Kc3Esh', 'integration': {'category': 'API', 'object': 'integration', 'id': '7FtS4J', 'name': 'API'}}], 'page': 0}

Otherwise we see the class object bring printed out:

```
print(client.Metrics.get_metrics(page=0,
                                 count=1))

```
> <klaviyo.api_helper.KlaviyoAPIResponse object at 0x10ff616a0> 

A customer reached out about this so I am bringing this up here. Was this by design? If so, I think we would need to update the readme.

**Comment by remstone7** [comment]
yes this was by design, i will update the README w/ a response section, thanks for bringing this up!

**Comment by remstone7** [comment]
https://github.com/klaviyo/python-klaviyo/pull/24

**Comment by remstone7** [comment]
merged in, all set
