### ISSUE TITLE
Pip install klaviyo not working.

### ISSUE THREAD

**Issue by ArtiShrivastava** [klaviyo/python-klaviyo#26]
Hi Team. When I am installing the kalviyo package, it copies these two files only __init__.py  and middleware.py . The remaining files (api.py, api_helper.py, lists.py, public.py, metrics.py, profiles.py) are not copied inside klaviyo folder on installations. Due to this I am facing issue while using track APIs and Metrcis APIs.
Is it because I am not using Django framework?

**Comment by remstone7** [comment]
@ArtiShrivastava what version of the package are you? I just did a install on a fresh env and worked as expected

```
(py-kl-test) ~/Desktop/kl$ python
Python 3.6.5 (default, Jun 26 2018, 07:46:16) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import klaviyo
>>> klaviyo.__version__
'3.0.0'
>>> klaviyo.api 
<module 'klaviyo.api' from '/Users/user/.pyenv/versions/py-kl-test/lib/python3.6/site-packages/klaviyo/api.py'>
```

maybe try `pip install --upgrade klaviyo` ?

**Comment by ArtiShrivastava** [comment]
![image](https://user-images.githubusercontent.com/20041351/86781180-31f6f500-c07b-11ea-8e9a-35bc0d736fde.png)
I am using python 2.7.

**Comment by remstone7** [comment]
Thanks, should be resolved now - i only updated the distribution list for python3, not python2.

```
(python-klaviyo-27) $ python -V
Python 2.7.15
(python-klaviyo-27) $ pip search klaviyo
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
klaviyo (3.0.1)      - Python API for Klaviyo
  INSTALLED: 3.0.1 (latest)
```

**Comment by ArtiShrivastava** [comment]
Thanks. It's working.
