### ISSUE TITLE
Can't return more than 100 metrics u sing get_metrics_timeline()

### ISSUE THREAD

**Issue by kellybjames** [klaviyo/python-klaviyo#31]
I can't seem to get more than 100 metrics using the get_metrics_timeline method.

Sample:

metrics = client.Metrics.get_metrics_timeline(count=101)

Am I missing something?

**Comment by klaviyojad** [comment]
@kellybjames sorry for the confusion.  The logic in our code only allows figures up to 100.  Anything greater would be defaulted to 100

**Comment by kellybjames** [comment]
Thank you!
