### ISSUE TITLE
Unable to pull event level conversion data using metrics API

### ISSUE THREAD

**Issue by ContentBean** [klaviyo/python-klaviyo#34]
Hello, 

It seems I'm only able to pull metrics with a maximum resolution of 1 day filtered by attribution. I'd like to be able to pull Placed Order metrics in such a way that I can link each attributed order to specific person. 

It seems like Klaviyo does this on the web platform – is this possible via API?

**Comment by ContentBean** [comment]
On a related note, it seems like attributed message data via the API only returns the results for 25 campaigns, which is the same as web portal. 

There doesn't seem to be a description of how those campaigns are filtered.

**Comment by remstone7** [comment]
Hey @ContentBean - I'd recommend opening up a support ticket [https://help.klaviyo.com/hc/en-us/articles/115001002272-How-to-Contact-Support](url) since your questions may be more geared toward the account data than the specific sdk.
