### ISSUE TITLE
Bug on Identify API

### ISSUE THREAD

**Issue by abishekcodes** [klaviyo/python-klaviyo#41]
Hi I noticed a bug on Public.identify function Line 122 
https://github.com/klaviyo/python-klaviyo/blob/master/klaviyo/public.py#L122
Here it should be 
if <del>id</del> external_id: properties['id'] = external_id
Could you please check

**Comment by remstone7** [comment]
@abishekcodes this is fixed in v3.1.3 which has been published

**Comment by abishekcodes** [comment]
Thank you for your prompt response @remstone7
